defaults:
  prompt: bnotes
  summary: mbn
  title: mtitle
prompts:
  bnotes:
    prompt: Write comprehensive bulleted notes summarizing the provided text, with
      headings and terms in bold.
  clean:
    prompt: Repeat back this text exactly, remove only garbage characters that do
      not contribute to the flow of text. Output only the main text content, condensed
      onto a single line. If you encounter any chapter boundaries or subheadings,
      start a new line beginning with its title.
  concise:
    prompt: Repeat the provided passage, with Concision.
  md:
    prompt: 'Print these notes in proper markdown format, with headings marked as
      bold with double asterisks and terms in bold also, and bullet points as `-`.
      Print the notes exactly, word-for-word, do not elaborate, do not add headings
      with #'
  research:
    prompt: Does this text make any arguments? If so, list them here.
  sum:
    prompt: Comprehensive bulleted notes with headings and terms in bold.
  teacher:
    prompt: 'Write a list of questions that can be answered by 3rd graders who are
      reading the provided text. Topics we like to focus on include: Main idea, supporting
      details, Point of view, Theme, Sequence, Elements of fiction (setting, characters,
      BME)'
title_generation:
  prompt: Write a title with fewer than 11 words to concisely describe this selection.
